const CLASS_TEXT_COMMENT = 'TextComment'
const CLASS_VOICE_RECORDING = 'VoiceRecording'
const CLASS_SYSTEM_ACTION = 'SystemAction'

export { CLASS_TEXT_COMMENT, CLASS_VOICE_RECORDING, CLASS_SYSTEM_ACTION }
